"""empty message

Revision ID: 15f82b3eac4a
Revises: 434c986cc16e
Create Date: 2024-05-27 10:07:37.548985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15f82b3eac4a'
down_revision = '434c986cc16e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cultural_places_latitude', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cultural_places_longitude', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tourist_attractions_latitude', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tourist_attractions_longitude', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('restaurants_latitude', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('restaurants_longitude', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('bars_latitude', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('bars_longitude', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('places_of_interest_latitude', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('places_of_interest_longitude', sa.Text(), nullable=True))
        batch_op.alter_column('city_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.alter_column('city_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('places_of_interest_longitude')
        batch_op.drop_column('places_of_interest_latitude')
        batch_op.drop_column('bars_longitude')
        batch_op.drop_column('bars_latitude')
        batch_op.drop_column('restaurants_longitude')
        batch_op.drop_column('restaurants_latitude')
        batch_op.drop_column('tourist_attractions_longitude')
        batch_op.drop_column('tourist_attractions_latitude')
        batch_op.drop_column('cultural_places_longitude')
        batch_op.drop_column('cultural_places_latitude')

    # ### end Alembic commands ###
