"""empty message

Revision ID: 3383e4446f9b
Revises: 81bc913761fb
Create Date: 2024-05-26 22:23:45.961543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3383e4446f9b'
down_revision = '81bc913761fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cultural_places', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tourist_attractions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('restaurants', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('bars', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('places_of_interest', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.drop_column('places_of_interest')
        batch_op.drop_column('bars')
        batch_op.drop_column('restaurants')
        batch_op.drop_column('tourist_attractions')
        batch_op.drop_column('cultural_places')

    # ### end Alembic commands ###
