"""empty message

Revision ID: 434c986cc16e
Revises: da2d3f330776
Create Date: 2024-05-26 22:57:44.253292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '434c986cc16e'
down_revision = 'da2d3f330776'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tourist_attraction')
    op.drop_table('bar')
    op.drop_table('restaurant')
    op.drop_table('cultural_place')
    op.drop_table('place_of_interest')
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cultural_places', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tourist_attractions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('restaurants', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('bars', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('places_of_interest', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('accommodation', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('transportation', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.drop_column('transportation')
        batch_op.drop_column('accommodation')
        batch_op.drop_column('places_of_interest')
        batch_op.drop_column('bars')
        batch_op.drop_column('restaurants')
        batch_op.drop_column('tourist_attractions')
        batch_op.drop_column('cultural_places')

    op.create_table('place_of_interest',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('city_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cultural_place',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('city_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restaurant',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('city_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bar',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('city_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tourist_attraction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('city_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
