"""Add places_of_interest to City model

Revision ID: 60c757e8df6a
Revises: 2ceb892a5853
Create Date: 2024-05-23 15:27:36.697453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60c757e8df6a'
down_revision = '2ceb892a5853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.add_column(sa.Column('places_of_interest', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.drop_column('places_of_interest')

    # ### end Alembic commands ###
