"""empty message

Revision ID: 7031c15c9580
Revises: 2b1fc633e991
Create Date: 2024-05-23 17:34:46.241518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7031c15c9580'
down_revision = '2b1fc633e991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('birthdate', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('gender')
        batch_op.drop_column('birthdate')
        batch_op.drop_column('phone')
        batch_op.drop_column('country')
        batch_op.drop_column('city')

    # ### end Alembic commands ###
