"""empty message

Revision ID: 81bc913761fb
Revises: d9f6d250a57c
Create Date: 2024-05-26 22:16:06.378651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81bc913761fb'
down_revision = 'd9f6d250a57c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.drop_column('cultural_places')
        batch_op.drop_column('places_of_interest')
        batch_op.drop_column('tourist_attractions')
        batch_op.drop_column('bars')
        batch_op.drop_column('restaurants')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurants', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('bars', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('tourist_attractions', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('places_of_interest', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('cultural_places', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
