"""empty message

Revision ID: abde53926582
Revises: 15f82b3eac4a
Create Date: 2024-05-27 13:15:31.089579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abde53926582'
down_revision = '15f82b3eac4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.alter_column('city_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('restaurants_longitude')
        batch_op.drop_column('bars_latitude')
        batch_op.drop_column('tourist_attractions_longitude')
        batch_op.drop_column('restaurants_latitude')
        batch_op.drop_column('places_of_interest_latitude')
        batch_op.drop_column('cultural_places_latitude')
        batch_op.drop_column('bars_longitude')
        batch_op.drop_column('places_of_interest_longitude')
        batch_op.drop_column('cultural_places_longitude')
        batch_op.drop_column('tourist_attractions_latitude')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tourist_attractions_latitude', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('cultural_places_longitude', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('places_of_interest_longitude', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('bars_longitude', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('cultural_places_latitude', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('places_of_interest_latitude', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('restaurants_latitude', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('tourist_attractions_longitude', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('bars_latitude', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('restaurants_longitude', sa.TEXT(), nullable=True))
        batch_op.alter_column('city_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
