"""empty message

Revision ID: e4e7d7342272
Revises: cd3da74bc3bb
Create Date: 2024-05-26 13:36:04.622003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4e7d7342272'
down_revision = 'cd3da74bc3bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accommodation', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.drop_column('accommodation')

    # ### end Alembic commands ###
